### ISSUE TITLE
SSL connection fails (not sure if local python issue)

### ISSUE THREAD

**Issue by alisneaky** [clarencecastillo/alfred-powerthesaurus#13]
Disabling SSL verification didn't impact this. Checked the Cert status which was green.

`UG    Starting new HTTPS connection (1): api.powerthesaurus.org:443
From cffi callback <function _verify_callback at 0x1069129b0>:
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/OpenSSL/SSL.py", line 309, in wrapper
    _lib.X509_up_ref(x509)
AttributeError: 'module' object has no attribute 'X509_up_ref'
08:18:10 workflow.py:2080 ERROR    HTTPSConnectionPool(host='api.powerthesaurus.org', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', 'ssl3_get_server_certificate', 'certificate verify failed')],)",),))
Traceback (most recent call last):
  File "/Users/ali-work/OneDrive - Telstra/Alfred Workflows/Alfred.alfredpreferences/workflows/user.workflow.B5FD5BEB-A9D5-4C41-8397-804617378D4A/workflow/workflow.py", line 2073, in run
    func(self)
  File "powerthesaurus.py", line 88, in main
    term = pt.search_query_match(query)
  File "/Users/ali-work/OneDrive - Telstra/Alfred Workflows/Alfred.alfredpreferences/workflows/user.workflow.B5FD5BEB-A9D5-4C41-8397-804617378D4A/api.py", line 118, in search_query_match
    terms = self.search_query(query)
  File "/Users/ali-work/OneDrive - Telstra/Alfred Workflows/Alfred.alfredpreferences/workflows/user.workflow.B5FD5BEB-A9D5-4C41-8397-804617378D4A/api.py", line 112, in search_query
    r = requests.post(self.api_url, json=params, headers=self.request_headers, verify=PowerThesaurus.VERIFY_SSL)
  File "./lib/requests/api.py", line 119, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "./lib/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "./lib/requests/sessions.py", line 530, in request
    resp = self.send(prep, **send_kwargs)
  File "./lib/requests/sessions.py", line 643, in send
    r = adapter.send(request, **kwargs)
  File "./lib/requests/adapters.py", line 514, in send
    raise SSLError(e, request=request)
SSLError: HTTPSConnectionPool(host='api.powerthesaurus.org', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', 'ssl3_get_server_certificate', 'certificate verify failed')],)",),))
08:18:10 workflow.py:2082 INFO     for assistance, see: https://github.com/clarencecastillo/alfred-powerthesaurus
08:18:10 workflow.py:2103 DEBUG    ---------- finished in 0.873s ----------
[08:18:10.890] Power Thesaurus[Script Filter] {"items": [{"valid": false, "subtitle": "HTTPSConnectionPool(host='api.powerthesaurus.org', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLError(\"bad handshake: Error([('SSL routines', 'ssl3_get_server_certificate', 'certificate verify failed')],)\",),))", "icon": {"path": "/System/Library/CoreServices/CoreTypes.bundle/Contents/Resources/AlertStopIcon.icns"}, "title": "Error in workflow 'Power Thesaurus'"}]}`

**Comment by alisneaky** [comment]
I can see it's using my python 2.7 version instead of python 3 which i've also got installed. Any way to fix it?

**Comment by clarencecastillo** [comment]
I believe all [Alfred-Workflow](https://github.com/deanishe/alfred-workflow) extensions use the pre-installed Python 2.7 so that's expected. As for the SSL error, the current certificate they send over is indeed valid. 

Any chance your machine's date/time is not set correctly?

**Comment by alisneaky** [comment]
machine's date and time is correct. I've got other workflows calling api's fine. Changing the variable doesn't seem to have an effect either.

**Comment by learn2reid** [comment]
Having an issue suddenly with SSL as well.

```
SSLError: HTTPSConnectionPool(host='api.powerthesaurus.org', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLError(1, u'[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:727)'),))
```

**Comment by learn2reid** [comment]
> Having an issue suddenly with SSL as well.
> 
> ```
> SSLError: HTTPSConnectionPool(host='api.powerthesaurus.org', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLError(1, u'[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:727)'),))
> ```

Fixed by installing requirements in workflow folder. The issue was:
https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings.

Update: this actually did not fix the problem. Any update?

**Comment by leadingendeavors** [comment]
I am getting this issue as well for the past few weeks. any leads on a fix?

**Comment by paultiomosquito** [comment]
I have been getting the error off and on and haven't been able to use the workflow for the past couple months. I did not have any success with setting the environment variable to false but when I hard-coded False for the VERIFY_SSL variable in in api.py, it solved the problem for me.

Not sure why SSL is erroring out because per the README, the SSL cert is verified: https://www.sslshopper.com/ssl-checker.html#hostname=api.powerthesaurus.org but I still had the problem.
