### ISSUE TITLE
urlopen error [SSL: TLSV1_ALERT_PROTOCOL_VERSION]

### ISSUE THREAD

**Issue by nmaxcom** [clarencecastillo/alfred-powerthesaurus#4]
I just installed this workflow, trying to use it for the first time but I get this error:

![image](https://user-images.githubusercontent.com/8936090/50377856-7bacf580-0625-11e9-92b8-ff0750b921c6.png)

I went debug mode in Alfred:

```Python traceback
[2018-12-22 20:09:57][input.scriptfilter] Queuing argument 'door'
[2018-12-22 20:09:58][input.scriptfilter] Script with argument '(null)' finished
[2018-12-22 20:09:58][ERROR: input.scriptfilter] Code 1: 20:09:57 workflow.py:2247 DEBUG    ---------- Powerthesaurus (1.1.0) ----------
20:09:57 powerthesaurus.py:87 DEBUG    query : u'door' u'syn'
20:09:57 powerthesaurus.py:42 DEBUG    Cache key : u'door' ['synonyms'] -> u'door_synonyms'
20:09:58 workflow.py:2266 ERROR    <urlopen error [SSL: TLSV1_ALERT_PROTOCOL_VERSION] tlsv1 alert protocol version (_ssl.c:590)>
Traceback (most recent call last):
  File "/Users/merl/Library/Application Support/Alfred 3/Alfred.alfredpreferences/workflows/user.workflow.E949D33D-97C7-4A21-84EB-36E531BA9433/workflow/workflow.py", line 2259, in run
    func(self)
  File "powerthesaurus.py", line 103, in main
    max_age=CACHE_MAX_AGE)
  File "/Users/merl/Library/Application Support/Alfred 3/Alfred.alfredpreferences/workflows/user.workflow.E949D33D-97C7-4A21-84EB-36E531BA9433/workflow/workflow.py", line 1890, in cached_data
    data = data_func()
  File "powerthesaurus.py", line 76, in get_words
    r = web.get(API_URL + query.replace(" ", "_") + "/" + query_type)
  File "/Users/merl/Library/Application Support/Alfred 3/Alfred.alfredpreferences/workflows/user.workflow.E949D33D-97C7-4A21-84EB-36E531BA9433/workflow/web.py", line 583, in get
    stream=stream)
  File "/Users/merl/Library/Application Support/Alfred 3/Alfred.alfredpreferences/workflows/user.workflow.E949D33D-97C7-4A21-84EB-36E531BA9433/workflow/web.py", line 571, in request
    return Response(req, stream)
  File "/Users/merl/Library/Application Support/Alfred 3/Alfred.alfredpreferences/workflows/user.workflow.E949D33D-97C7-4A21-84EB-36E531BA9433/workflow/web.py", line 214, in __init__
    self.raw = urllib2.urlopen(request)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 437, in open
    response = meth(req, response)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 550, in http_response
    'http', request, response, code, msg, hdrs)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 469, in error
    result = self._call_chain(*args)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 656, in http_error_302
    return self.parent.open(new, timeout=req.timeout)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 431, in open
    response = self._open(req, data)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 449, in _open
    '_open', req)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 1240, in https_open
    context=self._context)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 1197, in do_open
    raise URLError(err)
URLError: <urlopen error [SSL: TLSV1_ALERT_PROTOCOL_VERSION] tlsv1 alert protocol version (_ssl.c:590)>
20:09:58 workflow.py:2268 INFO     for assistance, see: https://github.com/clarencecastillo/alfred-powerthesaurus
20:09:58 workflow.py:2289 DEBUG    ---------- finished in 0.999s ----------
[2018-12-22 20:09:58][input.scriptfilter] <?xml version="1.0" encoding="utf-8"?>
<items><item valid="no"><title>Error in workflow 'Powerthesaurus'</title><subtitle>&lt;urlopen error [SSL: TLSV1_ALERT_PROTOCOL_VERSION] tlsv1 alert protocol version (_ssl.c:590)&gt;</subtitle><icon>/System/Library/CoreServices/CoreTypes.bundle/Contents/Resources/AlertStopIcon.icns</icon></item></items>
```

### Sys info
* macOS Sierra 10.12.6
* Python 3.7.1
* pip 18.1 from /miniconda3/lib/python3.7/site-packages/pip (python 3.7)

**Comment by ocundale** [comment]
I get the same error (Alfred 4 / macOS Sierra 10.12.6 / Python 2.7.10)

**Comment by clarencecastillo** [comment]
Please try it again with the new [release](https://github.com/clarencecastillo/alfred-powerthesaurus/releases/tag/v2.1.0).  Should fix all connection related issues.
